references:
  colors:
    dark: &onedark
      primary:
        background: '#282c34'
        foreground: '#abb2bf'

      normal:
        black:   '#282c34'
        red:     '#e06c75'
        green:   '#98c379'
        yellow:  '#e5c07b'
        blue:    '#61afef'
        magenta: '#c678dd'
        cyan:    '#56b6c2'
        white:   '#abb2bf'

      bright:
        black:   '#5c6370'
        red:     '#be5046'
        green:   '#98c379'
        yellow:  '#d19a66'
        blue:    '#61afef'
        magenta: '#c678dd'
        cyan:    '#56b6c2'
        white:   '#abb2bf'

    dark: &onelight
      primary:
        background: '#fafafa'
        foreground: '#383a42'

      normal:
        black:   '#fafafa'
        red:     '#e45649'
        green:   '#50a14f'
        yellow:  '#986801'
        blue:    '#4078f2'
        magenta: '#a626a4'
        cyan:    '#0184bc'
        white:   '#abb2bf'

      bright:
        black:   '#fafafa'
        red:     '#ca1243'
        green:   '#50a14f'
        yellow:  '#c18401'
        blue:    '#4078f2'
        magenta: '#a626a4'
        cyan:    '#0184bc'
        white:   '#abb2bf'

window:
  startup_mode: Maximized

shell:
  program: /usr/local/bin/fish
  args:
    - -c
    - "/usr/local/bin/tmux attach || /usr/local/bin/tmux"

font:
  size: 17.0

  normal:
    family: Source Code Variable
    style: Regular

  bold:
    family: Source Code Variable
    style: Bold

colors: *onedark
