[colors.bright]
black = "#a0a1a7"
blue = "#4078f2"
cyan = "#0184bc"
green = "#50a14f"
magenta = "#a626a4"
red = "#ca1243"
yellow = "#c18401"
white = "#383a42"

[colors.normal]
black = "#fafafa"
blue = "#4078f2"
cyan = "#0184bc"
green = "#50a14f"
magenta = "#a626a4"
red = "#e45649"
yellow = "#986801"
white = "#696c77"

[colors.primary]
background = "#fafafa"
foreground = "#383a42"
