[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#be5046"
yellow = "#e5c07b"
white = "#abb2bf"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
yellow = "#d19a66"
white = "#828997"

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

