[colors.bright]
black = "#383a42"
blue = "#4078f2"
cyan = "#0184bc"
green = "#50a14f"
magenta = "#a626a4"
red = "#ca1243"
white = "#abb2bf"
yellow = "#c18401"

[colors.normal]
black = "#383a42"
blue = "#4078f2"
cyan = "#0184bc"
green = "#50a14f"
magenta = "#a626a4"
red = "#e45649"
white = "#abb2bf"
yellow = "#986801"

[colors.primary]
background = "#fafafa"
foreground = "#383a42"
